### ISSUE TITLE
ゲーム終了画面をもっと豪華にする

### ISSUE THREAD

**Issue by mktakuya** [ggjsap-2016-t3/main-game#31]

**Comment by tanitta** [comment]
ゲームクリア時の画面にクレジットとして開発に携わった人の名前を表示したいと思います。各自名前のascii文字列を書いてこのissueにコメントしてください:)

**Comment by maid-san** [comment]
homomaid

please!

**Comment by yassu** [comment]
Please write as
yassu 
for me.

**Comment by mktakuya** [comment]
mktakuya

**Comment by manzyun** [comment]
Please write as 
manzyun

**Comment by nasa9084** [comment]
nasa9084
でお願いしまーす

**Comment by tanitta** [comment]
開発者のクレジット追加してスコアの表示も行いました✌
