### ISSUE TITLE
ドット絵作り

### ISSUE THREAD

**Issue by mktakuya** [ggjsap-2016-t3/main-game#8]
仕様などここに

**Comment by tanitta** [comment]
map.pngは0が不可侵領域、1は移動可能な領域、2がスタート地点、3がゴール地点です。

**Comment by tanitta** [comment]
robo.pngに他の姿勢とアクションのシートを追加しました。
0が前向き、1,2が下へ歩行
3が後ろ向き、4,5が上へ歩行
6が左向き、7､8が左へ歩行
9が左向き、10､11が左へ歩行
です。

**Comment by mktakuya** [comment]
@tanitta map.pngは、0が移動可能な領域、1は不可侵領域、2がスタート地点、3がゴール地点という感じでお願いします！
